services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${SAO_DB_USER}
      POSTGRES_PASSWORD: ${SAO_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    profiles:
      - dev
      - prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SAO_DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./docker/db-init:/docker-entrypoint-initdb.d

  web-dev:
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    depends_on:
      - db
    environment:
      SAO_PROFILE: dev
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      SAO_DB_USER: ${SAO_DB_USER}
      SAO_DB_PASSWORD: ${SAO_DB_PASSWORD}
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"

  web-prod:
    profiles:
      - prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - SAO_APPUSER=${SAO_APPUSER}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      SAO_PROFILE: prod
    ports:
      - "80:10000"

volumes:
  postgres_data:  # 永続化ボリューム